Repository SuessLabs/Linux.Bluetooth, pull requests merged in 2024-09, with the labels that each got.

#33 Update DBus package
  src/Linux.Bluetooth/Linux.Bluetooth.csproj
Labels: enhancement

#36 Uncatched exception in DeviceExtension.WaitForPropertyValueInternal()
  src/Linux.Bluetooth/Extensions/DeviceExtensions.cs
Labels: enhancement

#38 Sync NuGets
  README.md
  src/Linux.Bluetooth.Tests/Linux.Bluetooth.Tests.csproj
Labels: enhancement

#40 Release 5.67
  .github/CONTRIBUTING.md
  .github/Code-of-Conduct.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/Security.md
  README.md
  build.ps1
  script/Linux.Bluetooth.nuspec
  src/Linux.Bluetooth/Linux.Bluetooth.csproj
Labels: 5.x

#43 Fix Logo Path for NuGet.org
  README.md
Labels: enhancement, 5.x

#35 Update Packages
  Directory.Build.props
  Directory.Packages.props
  Linux.Bluetooth.sln
  samples/BleTester/App.axaml.cs
  samples/BleTester/Assets/avalonia-logo.ico
  samples/BleTester/Assets/logo.ico
  samples/BleTester/BleTester.csproj
  samples/BleTester/Program.cs
  samples/BleTester/ViewModels/MainViewModel.cs
  samples/BleTester/Views/MainView.axaml
  samples/BleTester/Views/MainWindow.axaml
  samples/printDeviceInfo/printDeviceInfo.csproj
  samples/scan/scan.csproj
  samples/subscribeToCharacteristic/subscribeToCharacteristic.csproj
  src/Linux.Bluetooth.ManualTest/Linux.Bluetooth.ManualTest.csproj
  src/Linux.Bluetooth.Tests/Linux.Bluetooth.Tests.csproj
  src/Linux.Bluetooth/CloseSafeHandle.cs
  src/Linux.Bluetooth/Linux.Bluetooth.csproj
Labels: 6.0.x

#45 Update README.md
  README.md
Labels: documentation, 6.0.x

#47 Update README.md
  README.md
Labels: 6.0.x

#50 Update feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, 6.0.x

#51 Update issue.md
  .github/ISSUE_TEMPLATE/issue.md
Labels: documentation

#53 Update README.md
  README.md
Labels: documentation
